# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Python SDK surface for NeMo Fabric."""

from nemo_fabric.client import Fabric
from nemo_fabric.errors import (
    FabricCapabilityError,
    FabricConfigError,
    FabricError,
    FabricNativeUnavailableError,
    FabricRuntimeError,
    FabricStateError,
)
from nemo_fabric.session import Session, SessionStatus
from nemo_fabric.models import (
    EnvironmentConfigModel,
    FabricBaseModel,
    FabricConfigModel,
    FabricProfileConfigModel,
    HarnessConfigModel,
    McpConfigModel,
    McpServerConfigModel,
    MetadataConfigModel,
    ModelConfigModel,
    ProfileRegistryConfigModel,
    RunRequestModel,
    RuntimeConfigModel,
    SkillConfigModel,
    TelemetryConfigModel,
)
from nemo_fabric.types import (
    AdapterInfo,
    ArtifactManifest,
    ArtifactRef,
    DoctorCheck,
    DoctorReport,
    EffectiveConfig,
    EnvironmentConfig,
    ErrorInfo,
    FabricConfig,
    FabricEvent,
    HarnessConfig,
    McpConfig,
    MetadataConfig,
    RunPlan,
    RunRequest,
    RunResult,
    RuntimeCapabilities,
    RuntimeHandle,
    RuntimeConfig,
    RuntimeUpdate,
    RuntimeUpdateResult,
    SessionHandle,
    SkillConfig,
    TelemetryConfig,
    TelemetryRef,
)

__all__ = [
    "AdapterInfo",
    "ArtifactManifest",
    "ArtifactRef",
    "DoctorCheck",
    "DoctorReport",
    "EffectiveConfig",
    "EnvironmentConfig",
    "EnvironmentConfigModel",
    "ErrorInfo",
    "Fabric",
    "FabricBaseModel",
    "FabricConfig",
    "FabricConfigModel",
    "FabricCapabilityError",
    "FabricConfigError",
    "FabricError",
    "FabricEvent",
    "FabricProfileConfigModel",
    "HarnessConfig",
    "HarnessConfigModel",
    "McpConfig",
    "McpConfigModel",
    "McpServerConfigModel",
    "MetadataConfig",
    "MetadataConfigModel",
    "ModelConfigModel",
    "ProfileRegistryConfigModel",
    "FabricNativeUnavailableError",
    "FabricRuntimeError",
    "FabricStateError",
    "RunPlan",
    "RunRequest",
    "RunRequestModel",
    "RunResult",
    "RuntimeCapabilities",
    "RuntimeHandle",
    "RuntimeConfig",
    "RuntimeConfigModel",
    "RuntimeUpdate",
    "RuntimeUpdateResult",
    "Session",
    "SessionHandle",
    "SessionStatus",
    "SkillConfig",
    "SkillConfigModel",
    "TelemetryConfig",
    "TelemetryConfigModel",
    "TelemetryRef",
]
