def version() -> str: ...
def validate(path: str) -> str: ...
def inspect(path: str) -> str: ...
def plan(path: str, profile: str | list[str] | None = None) -> str: ...
def doctor(path: str, profile: str | list[str] | None = None) -> str: ...
def run(
    path: str,
    profile: str | list[str] | None = None,
    input_text: str | None = None,
    input_file: str | None = None,
    request_json: str | None = None,
    request_file: str | None = None,
) -> str: ...
