//! JSON Schema generation for the public Fabric contract.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use schemars::schema_for;
use serde_json::Value;

use crate::config::{AdapterDescriptor, FabricConfig, ProfileConfig, RunPlan};
use crate::error::{FabricError, Result};
use crate::runtime::{ArtifactManifest, RunRequest, RunResult};

/// Public schema snapshots generated by Fabric.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SchemaName {
    /// Base `agent.yaml` schema.
    Agent,
    /// Profile overlay schema.
    Profile,
    /// Adapter descriptor schema.
    AdapterDescriptor,
    /// Resolved run plan schema.
    RunPlan,
    /// Runtime request schema.
    RunRequest,
    /// Runtime result schema.
    RunResult,
    /// Artifact manifest schema.
    ArtifactManifest,
}

impl SchemaName {
    /// All public schemas in stable output order.
    pub const ALL: [Self; 7] = [
        Self::Agent,
        Self::Profile,
        Self::AdapterDescriptor,
        Self::RunPlan,
        Self::RunRequest,
        Self::RunResult,
        Self::ArtifactManifest,
    ];

    /// Stable file stem for this schema.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Agent => "agent",
            Self::Profile => "profile",
            Self::AdapterDescriptor => "adapter-descriptor",
            Self::RunPlan => "run-plan",
            Self::RunRequest => "run-request",
            Self::RunResult => "run-result",
            Self::ArtifactManifest => "artifact-manifest",
        }
    }

    /// Snapshot filename for this schema.
    pub fn filename(self) -> String {
        format!("{}.schema.json", self.as_str())
    }

    /// Parse a schema name from CLI/user input.
    pub fn parse(value: &str) -> Result<Self> {
        match value {
            "agent" => Ok(Self::Agent),
            "profile" => Ok(Self::Profile),
            "adapter-descriptor" | "adapter_descriptor" => Ok(Self::AdapterDescriptor),
            "run-plan" | "run_plan" => Ok(Self::RunPlan),
            "run-request" | "run_request" => Ok(Self::RunRequest),
            "run-result" | "run_result" => Ok(Self::RunResult),
            "artifact-manifest" | "artifact_manifest" => Ok(Self::ArtifactManifest),
            _ => Err(FabricError::UnknownSchema {
                schema: value.to_string(),
                available: Self::ALL
                    .iter()
                    .map(|schema| schema.as_str().to_string())
                    .collect(),
            }),
        }
    }
}

/// Generate one schema as a JSON value.
pub fn generate_schema(schema: SchemaName) -> Result<Value> {
    match schema {
        SchemaName::Agent => to_value(schema_for!(FabricConfig)),
        SchemaName::Profile => to_value(schema_for!(ProfileConfig)),
        SchemaName::AdapterDescriptor => to_value(schema_for!(AdapterDescriptor)),
        SchemaName::RunPlan => to_value(schema_for!(RunPlan)),
        SchemaName::RunRequest => to_value(schema_for!(RunRequest)),
        SchemaName::RunResult => to_value(schema_for!(RunResult)),
        SchemaName::ArtifactManifest => to_value(schema_for!(ArtifactManifest)),
    }
}

/// Generate all schemas keyed by stable schema name.
pub fn generate_all_schemas() -> Result<BTreeMap<String, Value>> {
    SchemaName::ALL
        .iter()
        .map(|schema| Ok((schema.as_str().to_string(), generate_schema(*schema)?)))
        .collect()
}

/// Generate one schema as pretty JSON.
pub fn generate_schema_json(schema: SchemaName) -> Result<String> {
    serde_json::to_string_pretty(&generate_schema(schema)?).map_err(FabricError::SerializeJson)
}

/// Write all schema snapshots to `directory`.
pub fn write_schema_snapshots(directory: impl AsRef<Path>) -> Result<Vec<PathBuf>> {
    let directory = directory.as_ref();
    std::fs::create_dir_all(directory).map_err(|source| FabricError::Write {
        path: directory.to_path_buf(),
        source,
    })?;
    let mut written = Vec::new();
    for schema in SchemaName::ALL {
        let path = directory.join(schema.filename());
        std::fs::write(&path, generate_schema_json(schema)?).map_err(|source| {
            FabricError::Write {
                path: path.clone(),
                source,
            }
        })?;
        written.push(path);
    }
    Ok(written)
}

fn to_value<T>(schema: T) -> Result<Value>
where
    T: serde::Serialize,
{
    serde_json::to_value(schema).map_err(FabricError::SerializeJson)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn schema_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../schemas")
    }

    #[test]
    fn schema_snapshots_match_generated_contract() {
        for schema in SchemaName::ALL {
            let path = schema_dir().join(schema.filename());
            let expected: Value = serde_json::from_str(
                &std::fs::read_to_string(&path)
                    .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display())),
            )
            .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()));
            let generated = generate_schema(schema).expect("schema generation");

            assert_eq!(generated, expected, "schema snapshot drifted: {schema:?}");
        }
    }

    #[test]
    fn all_schemas_are_available_by_stable_name() {
        let schemas = generate_all_schemas().expect("schema generation");

        for schema in SchemaName::ALL {
            assert!(schemas.contains_key(schema.as_str()), "missing {schema:?}");
            assert_eq!(
                SchemaName::parse(schema.as_str()).expect("known schema"),
                schema
            );
        }
    }
}
